leftnav:
- identifier: 97201615-57d4-4c5a-9098-a9446cb27d7c
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 64c0e042-1482-4cbc-bc20-e7952bc8f254
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 1f3f9f0f-79a4-4628-9334-9e10d34ae9bd
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 0f449cfe-c4fc-4a88-86ba-58c2cd920fdd
  name: Assignments
  url: /pages/assignments
  weight: 40
